services:
  db:
    image: postgres:alpine
    container_name: dirhamly-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dirhamly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dirhamly-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgres://postgres:dev@db:5432/dirhamly
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm drizzle-kit push --strict --verbose --force && pnpm dev"  

volumes:
  postgres_data:
