services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dirhamly-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dirhamlydb
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:alpine
    container_name: dirhamly-db
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
